version: '3.8'

services:
  db1:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'venkat_proven_pro'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: '1234'

  web:
    build: .
    image: proven_pro
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db1
    command: >
      sh -c "
        until mysqladmin ping -h db1 -uroot -p1234 --silent; do
          echo 'Waiting for MySQL...';
          sleep 2;
        done;
        python3 manage.py makemigrations &&
        python3 manage.py migrate &&
        python3 manage.py runserver 0.0.0.0:8000
      "