version: '3.8'

services:
  web:
    build: .
    command: gunicorn proven_pro.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DB_ENGINE=django.db.backends.mysql
      - DB_NAME=proven_django
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_HOST=localhost
      - DB_PORT=3306
      - SECRET_KEY='django-insecure-#*mj14g=sspa-*0b^7$$8^eax7%b5zn!_q+hl4rd=w^vc%u5bx'
      - EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=True
      - EMAIL_HOST_USER=pavimohan0105@gmail.com
      - EMAIL_HOST_PASSWORD=dyjw wsuu rguq xlhc
      - DEFAULT_FROM_EMAIL=pavimohan0105@gmail.com
      - EMAIL_TIMEOUT=30
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=proven_pro_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
