# Use slim Python image
FROM python:3.11-slim

# Don't write .pyc files and show logs in real time
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory inside the container
WORKDIR /app

# Install required system dependencies (for MySQL and building Python packages)
RUN apt-get update && apt-get install -y \
    default-libmysqlclient-dev \
    build-essential \
    pkg-config \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy and install dependencies
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt


COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

# Copy the full project code into the container
COPY . .

# Expose the port Django/Gunicorn will run on
EXPOSE 8000

# Default command to run the app
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "proven_pro.wsgi:application"]
